replicas: 1
minimumMasterNodes: 1
esJavaOpts: "-Xmx1g -Xms1g"
resources:
  requests:
    cpu: "100m"
    memory: "2Gi"
  limits:
    cpu: "1000m"
    memory: "2Gi"
volumeClaimTemplate:
  accessModes: [ "ReadWriteOnce" ]
  resources:
    requests:
      storage: 1Gi
  storageClassName: "standard"  # Or whatever your cluster uses

persistence:
  enabled: true  # change to false if you're testing and don't need volume


