jenkins:
  # Basic authentication
  auth:
    admin:
      username: "admin"
      password: "admin123"

  service:
    type: LoadBalancer
    ports:
      http: 80

  persistence:
    enabled: true
    size: 10Gi
    accessModes:
      - ReadWriteOnce
    storageClass: "efs-sc"

  plugins:
    - "kubernetes"
    - "workflow-aggregator"
    - "git"
    - "configuration-as-code"
    - "nodejs"
    - "slack"

  configuration: |
    jenkins:
      numExecutors: 0
      clouds:
        - kubernetes:
            name: "kubernetes"
            serverUrl: "https://kubernetes.default.svc.cluster.local"
            namespace: "jenkins"
            skipTlsVerify: true
            templates:
              - name: "kaniko-pod"
                namespace: "jenkins"
                label: "kaniko"
                yaml: |
                  apiVersion: v1
                  kind: Pod
                  spec:
                    serviceAccountName: jenkins
                    containers:
                    - name: kaniko
                      image: gcr.io/kaniko-project/executor:debug
                      command: ["/bin/sh"]
                      args: ["-c", "sleep 99d"]
                      env:
                      - name: AWS_DEFAULT_REGION
                        value: us-east-1
                    - name: aws-cli
                      image: amazon/aws-cli:latest
                      command: ["/bin/sh"]
                      args: ["-c", "sleep 99d"]

serviceAccount:
  create: true
  name: "jenkins"
  annotations:
    eks.amazonaws.com/role-arn: "arn:aws:iam::627073650373:role/JenkinsEKSRole"

rbac:
  create: true 