apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: redis-credentials
  annotations:
    argocd.argoproj.io/sync-wave: "1"  
spec:
  refreshInterval: 1h  
  secretStoreRef:
    name: aws-secret-store
    kind: SecretStore
  target:
    name: redis-secret  
    creationPolicy: Owner
  data:
  - secretKey: REDIS_PASSWORD  
    remoteRef:
      key: "prod/redis/credentials" 
      property: "password"  
  - secretKey: REDIS_USER  
    remoteRef:
      key: "prod/redis/credentials"
      property: "username"