apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: db-credentials
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-secret-store
    kind: SecretStore
  target:
    name: db-secret
  data:
  - secretKey: DB_USER
    remoteRef:
      key: "prod/db/credentials"
      property: "username"
  - secretKey: DB_PASSWORD
    remoteRef:
      key: "prod/db/credentials"
      property: "password"