apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: alldeployment
resources:
- secretResource.yaml
- secretStore.yaml
- mysql_ExternalSecret.yaml
- redis_ExternalSecret.yaml
- deployment.yaml
- mysql.yaml
- redis.yaml
- service.yaml
