apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: mysql-externalsecret
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-secretstore
    kind: SecretStore
  target:
    name: mysql-secret
    creationPolicy: Owner
  data:
  - secretKey: MYSQL_USER
    remoteRef:
      key: mysql-secret
      property: username
  - secretKey: MYSQL_PASSWORD
    remoteRef:
      key: mysql-secret
      property: password