apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: redis-externalsecret
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-secretstore
    kind: SecretStore
  target:
    name: redis-secret
    creationPolicy: Owner
  data:
  - secretKey: REDIS_USER
    remoteRef:
      key: redis-secret
      property: username
  - secretKey: REDIS_PASSWORD
    remoteRef:
      key: redis-secret
      property: password